global:
  vars:
    USDCUSD: '0xa1a8003936862e7a15092a91898d69fa8bce290c'
    USDCEUR: '0x206b25ea01e188ee243131afde526ba6e131a016'
    USDCBRL: '0x25f21a1f97607edf6852339fad709728cffb9a9d'
    EUROCEUR: '0x26076B9702885d475ac8c3dB3Bd9F250Dc5A318B'
    EURXOF: '0x40dc8528167557353fdcd98548ab2139a670dd0b'

chains:
  - id: celo
    label: celo
    httpRpcUrl: https://forno.celo.org
    contracts:
      SortedOracles: '0xefb84935239dacdecf7c5ba76d8de40b077b7b33'
      OracleHelper: '0x555a4D35328462bCadFD9558295F8E0C98FEdea0'
      BreakerBox: '0xec71b0Ac61b2a0B386B156396F3B7A8363F70707'
    vars:
      CELOUSD: '0x765de816845861e75a25fca122bb6898b8b1282a'
      CELOEUR: '0xd8763cba276a3738e6de85b4b3bf5fded6d6ca73'
      CELOBRL: '0xe8537a3d056da446677b9e9d6c5db704eaab4787'
      CELOXOF: '0x73F93dcc49cB8A239e2032663e9475dd5ef29A08'
  - id: celoAlfajores
    label: alfajores
    httpRpcUrl: https://alfajores-forno.celo-testnet.org
    contracts:
      SortedOracles: '0xfdd8bd58115ffbf04e47411c1d228ecc45e93075'
      OracleHelper: '0xf6D9C84e21b8B50c45013F99dED2637fd2b06f3b'
      BreakerBox: '0x259d8CeeB01E9346C830920052003f7D3B62Fd1C'
    vars:
      CELOUSD: '0x874069fa1eb16d44d622f2e0ca25eea172369bc1'
      CELOEUR: '0x10c892a6ec43a53e45d0b916b4b7d383b1b78c0f'
      CELOBRL: '0xe4d517785d091d3c54818832db6094bcc2744545'
      CELOXOF: '0xB0FA15e002516d0301884059c0aaC0F0C72b019D'
  - id: baklava
    label: baklava
    httpRpcUrl: https://baklava-forno.celo-testnet.org
    contracts:
      SortedOracles: '0x88a187a876290e9843175027902b9f7f1b092c88'
      OracleHelper: '0x02919803dba5D0fFb1AaB036b99E867bD9FB0d85'
      BreakerBox: '0xB881aF21C5A9ff8e8d5E4C900F67F066C6CB7936'
    vars:
      CELOUSD: '0x62492a644a588fd904270bed06ad52b9abfea1ae'
      CELOEUR: '0xf9ece301247ad2ce21894941830a2470f4e774ca'
      CELOBRL: '0x6a0eef2bed4c30dc2cb42fe6c5f01f80f7ef16d1'
      CELOXOF: '0x64c1D812673E93Bc036AdC3D547d9950696DA5Af'

metrics:
  - source: SortedOracles.numRates(address rateFeed)(uint256)
    schedule: 0/10 * * * * *
    type: gauge
    chains: all
    variants:
      - ['CELOUSD']
      - ['CELOEUR']
      - ['CELOBRL']
      - ['CELOXOF']
      - ['USDCUSD']
      - ['USDCEUR']
      - ['USDCBRL']
      - ['EUROCEUR']
      - ['EURXOF']
      
  - source: OracleHelper.deviation(address rateFeed)(uint256,uint256)
    schedule: 0/10 * * * * *
    type: gauge
    chains: all
    variants:
      - ['CELOUSD']
      - ['CELOEUR']
      - ['CELOBRL']
      - ['CELOXOF']
      - ['USDCUSD']
      - ['USDCEUR']
      - ['USDCBRL']
      - ['EUROCEUR']
      - ['EURXOF']
      
  - source: BreakerBox.getRateFeedTradingMode(address rateFeed)(uint8)
    schedule: 0/10 * * * * *
    type: gauge
    chains: all
    variants:
      - ['CELOUSD']
      - ['CELOEUR']
      - ['CELOBRL']
      - ['CELOXOF']
      - ['USDCUSD']
      - ['USDCEUR']
      - ['USDCBRL']
      - ['EUROCEUR']
      - ['EURXOF']

