chains:
  - id: celo
    label: celo
    httpRpcUrl: https://forno.celo.org
    contracts:
      SortedOracles: '0xefb84935239dacdecf7c5ba76d8de40b077b7b33'
      OracleHelper: '0x5B4B6ba128c7BA51d63eD7474A7b17492Fb28476'
    vars:
      CELOUSD: '0x765de816845861e75a25fca122bb6898b8b1282a'
      CELOEUR: '0xd8763cba276a3738e6de85b4b3bf5fded6d6ca73'
      CELOBRL: '0xe8537a3d056da446677b9e9d6c5db704eaab4787'
  - id: celoAlfajores
    label: alfajores
    httpRpcUrl: https://alfajores-forno.celo-testnet.org
    contracts:
      SortedOracles: '0xfdd8bd58115ffbf04e47411c1d228ecc45e93075'
      OracleHelper: '0x5B4B6ba128c7BA51d63eD7474A7b17492Fb28476'
    vars:
      CELOUSD: '0x874069fa1eb16d44d622f2e0ca25eea172369bc1'
      CELOEUR: '0x10c892a6ec43a53e45d0b916b4b7d383b1b78c0f'
      CELOBRL: '0xe4d517785d091d3c54818832db6094bcc2744545'
  - id: baklava
    label: baklava
    httpRpcUrl: https://baklava-forno.celo-testnet.org
    contracts:
      SortedOracles: '0x88a187a876290e9843175027902b9f7f1b092c88'
    vars:
      CELOUSD: '0x62492a644a588fd904270bed06ad52b9abfea1ae'
      CELOEUR: '0xf9ece301247ad2ce21894941830a2470f4e774ca'
      CELOBRL: '0x6a0eef2bed4c30dc2cb42fe6c5f01f80f7ef16d1'

metrics:
  - source: SortedOracles.numRates(address rateFeed)(uint256)
    schedule: 0/10 * * * * *
    type: gauge
    chains: all
    variants:
      - ['CELOUSD']
      - ['CELOEUR']
      - ['CELOBRL']
  - source: OracleHelper.deviation(address rateFeed)(uint256,uint256)
    schedule: 0/10 * * * * *
    type: gauge
    chains: ['celo']
    variants:
      - ['CELOUSD']
      - ['CELOEUR']
      - ['CELOBRL']
