steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ./template-agent.sh
    secretEnv:
      [
        'GRAFANA_AGENT_ENDPOINT',
        'GRAFANA_AGENT_USERNAME',
        'GRAFANA_AGENT_PASSWORD',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'grafana-agent.yaml']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/grafana-agent-endpoint/versions/1
      env: 'GRAFANA_AGENT_ENDPOINT'
    - versionName: projects/$PROJECT_ID/secrets/grafana-agent-username/versions/1
      env: 'GRAFANA_AGENT_USERNAME'
    - versionName: projects/$PROJECT_ID/secrets/grafana-agent-password/versions/1
      env: 'GRAFANA_AGENT_PASSWORD'
